{
 "title": "Solar PV System",
 "description": "https://github.com/JoshIPT/x1smart-influx",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "columns": [
      { "value": "value" },
      { "value": "time" }
     ],
     "queryText": "SELECT value,time FROM ac_power WHERE value < 8000",
     "table": "ac_power",
     "wheres": [
      { "value": "value < 8000" }
     ]
    },
    {
     "columns": [
      { "value": "value" },
      { "value": "time" }
     ],
     "queryText": "SELECT value,time FROM exported_power WHERE value < 8000",
     "table": "exported_power",
     "wheres": [
      { "value": "value < 8000" }
     ]
    },
    {
     "columns": [
      { "value": "value" },
      { "value": "time" }
     ],
     "queryText": "SELECT value,time FROM consumed_power WHERE value > -1",
     "table": "consumed_power",
     "wheres": [
      { "value": "value > -1" }
     ]
    }
   ]
  },
  {
   "title": "Grid Power (V)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "columns": [
      { "value": "value" }
     ],
     "queryText": "SELECT value FROM network_voltage",
     "table": "network_voltage",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Inverter Temp (°C)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "columns": [
      { "value": "value" }
     ],
     "queryText": "SELECT value FROM inverter_temp",
     "table": "inverter_temp",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "PV1 Current (A)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "columns": [
      { "value": "value" },
      { "value": "time" }
     ],
     "queryText": "SELECT value,time FROM iox.pv1_current",
     "table": "pv1_current",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "PV1 Power (W)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "columns": [
      { "value": "value" },
      { "value": "time" }
     ],
     "queryText": "SELECT value,time FROM pv1_power",
     "table": "pv1_power",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "PV2 Current (A)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "columns": [
      { "value": "value" },
      { "value": "time" }
     ],
     "queryText": "SELECT value,time FROM iox.pv2_current",
     "table": "pv2_current",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "PV2 Power (W)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "columns": [
      { "value": "value" },
      { "value": "time" }
     ],
     "queryText": "SELECT value,time FROM iox.pv2_power",
     "table": "pv2_power",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  }
 ]
}